[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyclip2playlist"
version = "0.1.0"
description = "Extract song information from clipboard text and create playlists"
readme = "README.md"
authors = [
    { name = "UntoastedToast" }
]
maintainers = [
    { name = "UntoastedToast" }
]
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "pyperclip>=1.8.2",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: X11 Applications :: GTK",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Utilities",
]

[project.urls]
Homepage = "https://github.com/UntoastedToast/PyClip2Playlist"
Repository = "https://github.com/UntoastedToast/PyClip2Playlist.git"

[project.scripts]
pyclip2playlist = "pyclip2playlist.gui:main"

[tool.setuptools]
packages = ["pyclip2playlist"]

[tool.setuptools.package-data]
pyclip2playlist = ["resources/app.ico"]
